# Generated by Django 5.2.4 on 2025-07-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_livro_autores_livro_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='editora',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editora',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
